# Generated by Django 3.2 on 2021-12-07 17:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'المؤلف',
                'verbose_name_plural': 'المؤلفين',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30, verbose_name='اسم القسم')),
                ('description', models.TextField(max_length=200, verbose_name='وصف القسم')),
                ('cat_color', models.CharField(max_length=15, verbose_name='لون القسم')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الاقسام',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='عنوان المقال')),
                ('description', models.TextField(max_length=200, verbose_name='وصف المقال')),
                ('image_main', models.ImageField(blank=True, default='default.png', upload_to='main-post/%y/%m/%d', verbose_name='صورة المقال')),
                ('image_url', models.URLField(blank=True, verbose_name='رابط صورة المقال')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوى المقال')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('show_in_home_first', models.BooleanField(default=False, verbose_name='طهور في أول مقدة الرئيسية')),
                ('show_in_home', models.BooleanField(default=False, verbose_name='طهور في مقدة الرئيسية')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='تاريخ الانشاء')),
                ('post_update', models.DateTimeField(auto_now=True, null=True)),
                ('views', models.IntegerField(default=0, null=True)),
                ('ads_num', models.IntegerField(default=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='المؤلف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categories', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'مقالات',
                'db_table': '',
                'ordering': ('-post_date',),
                'managed': True,
            },
        ),
    ]
